# ワークフローの名前(任意)
name: cc-solo-backend--github-actions
# masterブランチにPR
on:
  pull_request:
    branches:
      - master

# ワークフローで実行されるジョブをグループ化
jobs:
  #jobの名前を定義
  #静的解析してみる
  format:
    # 最新バージョンのmacOSランナーで実行するようにジョブを構成(Linuxにしたいときはubuntuなど可能)
    runs-on: macOS-latast
    steps:
      #リポジトリをチェックアウトしソースを利用可能にする
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install
        run: npm install
      - name: Prittier
        run: npm run pritter
      - name: ESLint
        run: npm run lint
